import {freshState, usable, filtered, shuffle, recordAnswer, stats, recommend, ticket, validateImport, paginateHistory} from './study.mjs';
import {openStorage} from './storage.mjs';
import {checkForUpdate} from './updates.mjs';
import {createDictation,evaluateAnswer,createAudioRecording,transcribeAudio,preferAudioRecording} from './voice.mjs';
const lectureNames=['Типы и выражения','Условия и циклы','Контейнеры и хеширование','Ссылки и копирование','Функции и аргументы','Классы и свойства','Исключения и контексты','Протоколы и ABC','Итераторы и генераторы','Коллекции и itertools','Декораторы и области','NumPy и pandas','Файлы и форматы','Тестирование'];
const navigation=[['home','⌂','Главная'],['progress','↗','Прогресс'],['settings','⚙','Настройки']];
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={guess:'Угадал',unsure:'Не уверен',know:'Знаю'}, byId=new Map(config.questions.map(q=>[q.id,q]));
let state,store,view='home',libraryLecture=null,onlyFavorites=false,historyPage=0,storageProblem='',registration,installPrompt,applyUpdate=false,updateStatus='',checkingUpdate=false;
let voiceListening=false,voiceError='',voiceRequest=null,draftSaveTimer=null,voiceAudioState='idle',voiceSpeechUnavailable=false,voiceAudioUsed=false;
const oralRecord=id=>{state.session.oral ||= {};return state.session.oral[id] ||= {draft:'',followDraft:'',turns:[]};};
const oralField=row=>row.turns[0]?.result.decision==='follow_up' && row.turns.length===1 ? 'followDraft' : 'draft';
const dictation=createDictation({
  onText:text=>{if(view!=='session'||state.session?.mode!=='voice')return;const row=oralRecord(state.session.ids[state.session.index]);row[oralField(row)]=text.slice(0,6000);if($('voice-answer'))$('voice-answer').value=row[oralField(row)];queueDraftSave();},
  onStatus:listening=>{voiceListening=listening;if(!listening){persist();render();}else render();},
  onError:message=>{voiceError=message;voiceSpeechUnavailable=true;},
});
const audioRecording=createAudioRecording({
  transcribe:(blob,options)=>transcribeAudio(config.voiceEndpoint,state.session.ids[state.session.index],blob,options),
  onText:text=>{if(view!=='session'||state.session?.mode!=='voice')return;const row=oralRecord(state.session.ids[state.session.index]);row[oralField(row)]=text.slice(0,6000);queueDraftSave();},
  onStatus:phase=>{voiceAudioState=phase;voiceListening=['permission','recording','stopping'].includes(phase);if(phase==='idle')persist();render();},
  onError:message=>{voiceError=message;render();},
});
const useAudioByDefault=audioRecording.supported&&(preferAudioRecording()||!dictation.supported);
const voiceBusy=()=>!!voiceRequest||voiceAudioState==='transcribing';
function queueDraftSave(){clearTimeout(draftSaveTimer);draftSaveTimer=setTimeout(()=>persist(),500);}
function stopVoice(){dictation.cancel();audioRecording.cancel();voiceListening=false;voiceRequest?.controller.abort();voiceRequest=null;voiceError='';voiceSpeechUnavailable=false;voiceAudioUsed=false;}
function voiceFeedback(result){const list=(key,title)=>result[key].length?`<div><strong>${title}</strong><ul>${result[key].map(text=>`<li>${esc(text)}</li>`).join('')}</ul></div>`:'';return `<div class="voice-feedback"><div class="voice-score"><strong>${result.score}/10</strong><span>${result.decision==='accepted'?'Зачтено':result.decision==='follow_up'?'Нужно уточнение':'Нужно повторить'}</span></div><p>${esc(result.summary)}</p>${list('strengths','Что верно')}${list('errors','Ошибки')}${list('additions','Что дополнить')}${result.followUp?`<p class="voice-follow-up"><strong>Уточняющий вопрос</strong><br>${esc(result.followUp)}</p>`:''}</div>`;}
function voicePanel(q){
  const row=oralRecord(q.id),graded=!!state.session.ratings[q.id],pending=row.turns.length===1&&row.turns[0].result.decision==='follow_up'&&!graded,busy=voiceBusy(),last=row.turns.at(-1);
  const permission=voiceAudioState==='permission',stopping=voiceAudioState==='stopping',audioMode=useAudioByDefault||voiceAudioUsed;
  const recordLabel=permission?'Отмена':stopping?'Завершаем запись…':voiceListening?'Остановить запись':'Ответить голосом';
  const recordAction=permission?'voice-cancel':voiceListening?'voice-stop':'voice-record';
  const message=voiceError|| (permission?'Разрешите доступ к микрофону в появившемся запросе.':stopping?'Завершаю запись…':voiceListening?'Идёт запись. Нажмите «Остановить запись», когда закончите.':voiceAudioState==='transcribing'?'Расшифровываю запись…':voiceRequest?'Проверяю смысл ответа…':!config.voiceEndpoint?'Сервер проверки ещё подключается.':!dictation.supported&&!audioRecording.supported?'Запись речи недоступна. Напечатайте ответ.':'Проверьте расшифровку перед отправкой.');
  return `<section class="voice-panel" aria-label="Устный ответ"><div class="voice-chat" tabindex="0" aria-label="Диалог с преподавателем">${row.turns.slice(-1).map(turn=>`<article class="voice-message student"><span class="small muted">${row.turns.length>1?'Ваше уточнение':'Ваш ответ'}</span><p>${esc(turn.answer)}</p></article><article class="voice-message teacher"><span class="small muted">Преподаватель · Groq</span>${voiceFeedback(turn.result)}</article>`).join('')}</div>${row.turns.length===2?`<details class="voice-earlier"><summary>Первый ответ и уточняющий вопрос</summary><p>${esc(row.turns[0].answer)}</p>${voiceFeedback(row.turns[0].result)}</details>`:''}${pending?`<p class="voice-follow-up"><strong>Уточнение:</strong> ${esc(row.turns[0].result.followUp)}</p>`:''}${graded?`<p class="voice-outcome" role="status"><strong>${last?last.result.score+'/10 · ':''}${state.session.ratings[q.id].correct?'Зачтено':'Нужно повторить'}</strong><span class="small muted">Оценка сохранена в прогрессе.</span></p>`:`<label class="field" for="voice-answer">${pending?'Ответ на уточняющий вопрос':'Ваш ответ'}<textarea id="voice-answer" rows="4" maxlength="6000" placeholder="Нажмите «Ответить голосом» или напечатайте ответ…" ${busy||voiceListening?'readonly':''}>${esc(row[oralField(row)])}</textarea></label><div class="voice-controls">${btn(recordLabel,recordAction,voiceListening?'danger':'',busy||stopping||!dictation.supported&&!audioRecording.supported?'disabled':'')}${btn(voiceAudioState==='transcribing'?'Расшифровываем…':voiceRequest?'Проверяем…':pending?'Проверить уточнение':'Проверить ответ','voice-check','primary',busy||voiceListening||!config.voiceEndpoint?'disabled':'')}${voiceSpeechUnavailable&&audioRecording.supported&&!audioMode?btn('Записать аудио','voice-audio','ghost',busy||voiceListening?'disabled':''):''}${audioRecording.canRetry?btn('Повторить расшифровку','voice-retry','ghost',busy||voiceListening?'disabled':''):''}</div><p class="small muted voice-status" role="status" aria-live="polite">${esc(message)}</p>${pending?btn('Завершить без уточнения','voice-skip','ghost',busy||voiceListening?'disabled':''):''}`}<p class="small muted voice-privacy">${audioMode?'Аудиозапись передаётся в Groq для расшифровки; после редактирования текст отправляется на проверку. Аудио не добавляется в историю приложения.':'Речь распознаёт браузер; для оценки текст ответа передаётся в Groq.'} Нужен интернет.</p>${last?`<details class="voice-reference"><summary>Эталонный ответ и объяснение</summary>${answers(q)}</details>`:''}</section>`;
}
async function saveVoiceGrade(q,result){if(state.session.ratings[q.id])return;const correct=result.decision==='accepted';state=recordAnswer(state,q,correct,null,Date.now(),state.session.id);const entry=state.history.at(-1);entry.assessment='groq';entry.score=result.score;state.session.ratings[q.id]={correct,confidence:null};await persist();}
async function checkVoice(q){if(voiceBusy()||voiceListening||state.session.ratings[q.id])return;const row=oralRecord(q.id),answer=row[oralField(row)].trim();if(!answer){toast('Сначала запишите или напечатайте ответ.');return;}const job={sessionId:state.session.id,questionId:q.id,controller:new AbortController()};voiceRequest=job;voiceError='';render();const timer=setTimeout(()=>job.controller.abort(),45000);try{const reply=await evaluateAnswer(config.voiceEndpoint,{questionId:q.id,answer,context:row.turns.length===1?row.turns[0].context:''},{signal:job.controller.signal});if(voiceRequest!==job||state.session.id!==job.sessionId)return;row.turns.push({answer,...reply});if(reply.result.decision!=='follow_up')await saveVoiceGrade(q,reply.result);else await persist();}catch(error){if(voiceRequest===job)voiceError=error.name==='AbortError'?'Проверка прервана. Ответ сохранён — попробуйте снова.':error.message;}finally{clearTimeout(timer);if(voiceRequest===job){voiceRequest=null;render();const chat=$('view').querySelector('.voice-chat');if(chat)chat.scrollTop=chat.scrollHeight;}}}
const pendingSession=()=>!!state.session&&(!state.session.finished||state.session.mode==='exam'&&!state.session.completed);
const pct=(a,b)=>b?Math.round(100*a/b):0;
const btn=(label,action,cls='',attrs='')=>`<button class="btn ${cls}" data-action="${action}" ${attrs}>${label}</button>`;
const badge=q=>`<span class="badge ${q.origin}">${q.origin==='original'?'Прошлый коллоквиум':'По лекциям'}</span>`;
const title=(heading,text)=>`<div class="section-heading"><div><h1>${heading}</h1><p>${text}</p></div></div>`;
const empty=(heading,text)=>`<div class="empty"><strong>${heading}</strong>${text}</div>`;
function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toast.timeout);toast.timeout=setTimeout(()=>{$('toast').hidden=true},4000);}
async function persist(){state.updatedAt=Date.now();$('save-state').textContent='Сохраняется…';try{await store.save(state);storageProblem='';$('save-state').textContent=store.mode==='indexeddb'?'Сохранено на устройстве':'Резервное сохранение';}catch(e){storageProblem=e.message;$('save-state').textContent='Не сохранено';$('storage-notice').textContent=e.message;}}
function theme(){const selected=state.settings.theme,dark=selected==='dark'||selected==='system'&&matchMedia('(prefers-color-scheme: dark)').matches;document.documentElement.dataset.theme=dark?'dark':'light';$('theme-toggle').textContent=dark?'☀':'☾';$('theme-toggle').setAttribute('aria-label',dark?'Включить светлую тему':'Включить тёмную тему');try{localStorage.setItem('python-colloquium-theme',JSON.stringify(selected));}catch{}}
function lectureRows(rows){return rows.map(l=>`<button class="lecture-row" data-action="open-lecture" data-lecture="${l.lecture}" aria-label="Все вопросы лекции ${l.lecture}: ${lectureNames[l.lecture-1]}"><span class="lecture-number">${String(l.lecture).padStart(2,'0')}</span><div><strong>${lectureNames[l.lecture-1]}</strong><div class="bar"><span style="width:${pct(l.seen,l.total)}%"></span></div></div><span class="lecture-completion"><strong>${pct(l.seen,l.total)}%</strong><span class="small muted">${l.seen}/${l.total}</span></span></button>`).join('');}
function metrics(s){return `<div class="metrics home-metrics">${[['Пройдено вопросов',s.seen,s.total,'Есть хотя бы одна оценка'],['Исходные вопросы',s.originals.seen,s.originals.total,'Из прошлого коллоквиума']].map(([label,n,total,note])=>`<div class="card metric"><span class="metric-label">${label}</span><div class="metric-value">${n}<span class="small muted"> / ${total}</span></div><span class="small muted">${note}</span></div>`).join('')}</div>`;}
function home(){const s=stats(config.questions,state),pending=pendingSession();return title('Всё начинается с понимания.','Ваши вопросы, ошибки и повторения — в одном месте. Занимайтесь в своём темпе.')+`<section class="hero"><div><div class="eyebrow">Python · 14 лекций</div><h2>${pending?'Продолжим с того же места?':'Небольшая тренировка. Глубокое понимание.'}</h2><p>${pending?'Сохранена незавершённая сессия: '+state.session.ids.length+' вопросов. Текущий — '+(state.session.index+1)+'.':'Начните с разнообразных вопросов. Следующая подборка учтёт ваши ошибки, уверенность и сроки повторения.'}</p><div class="button-row">${btn(pending?'Продолжить тренировку':'Стандартный режим',pending?'resume':'start-smart','primary')}${btn('Голосовое управление','voice-mode')}${btn('Исходные вопросы','originals')}${pending?btn('Закончить тренировку','end-session','ghost'):''}</div><p id="voice-mode-note" class="small muted">В голосовом режиме нейросеть проверяет ваш ответ и помогает его дополнить.</p>${filters()}</div><div class="ring" style="--angle:${pct(s.mastered,s.total)*3.6}deg"><div class="ring-center"><strong>${pct(s.mastered,s.total)}%</strong><span>закреплено</span></div></div></section>`+metrics(s)+`<section class="card"><div class="card-title"><h2>Освоение лекций</h2>${btn('Выбрать лекцию →','lecture-picker','ghost')}</div><div class="lecture-list home-lectures">${lectureRows(s.lectures)}</div><p class="small muted" style="margin-top:20px">Прохождение — доля вопросов, на которые вы дали оценённый ответ. Закрепление требует успешных повторений с интервалом.</p></section>`;}
function filters(){const s=state.settings,choices=(values,selected,name)=>values.map(v=>`<label class="filter-choice"><input type="checkbox" name="${name}" value="${esc(v)}" ${selected.includes(v)?'checked':''}><span>${esc(v)}</span></label>`).join('');return `<details class="filter-details"><summary>Настроить подборку · ${filtered(config.questions,s).length} вопросов доступно</summary><div class="filters"><label class="field">Количество<input id="filter-count" type="number" min="1" max="100" value="${s.count}"></label><label class="field">Происхождение<select id="filter-origin">${[['all','Все вопросы'],['original','Прошлый коллоквиум'],['new','По лекциям']].map(([v,t])=>`<option value="${v}" ${s.origin===v?'selected':''}>${t}</option>`).join('')}</select></label><label class="field">Умная подготовка<select id="smart-mode">${[['balanced','Сбалансированная'],['weak','Слабые темы'],['review','Повторение изученного'],['new','Новые вопросы'],['errors','Работа над ошибками']].map(([v,t])=>`<option value="${v}" ${s.smartMode===v?'selected':''}>${t}</option>`).join('')}</select></label><fieldset class="field choices"><legend>Типы вопросов</legend>${choices([...new Set(config.questions.map(q=>q.type))],s.types,'question-type')}</fieldset><fieldset class="field choices"><legend>Сложность</legend>${choices(['Простые','Средние','Сложные'],s.levels,'question-level')}</fieldset></div><p class="small muted" style="margin-top:20px">Лекции · пустой выбор означает все</p><div class="filter-lectures">${lectureNames.map((name,i)=>`<label class="check-pill"><input type="checkbox" name="lecture" value="${i+1}" ${s.lectures.includes(i+1)?'checked':''} aria-label="Лекция ${i+1}: ${name}"><span>${i+1}</span></label>`).join('')}</div><div class="button-row">${btn('Сбросить фильтры','clear-filters')}</div></details>`;}
function answers(q){return `<div class="answer rich"><h3>Ответ</h3>${q.answerHtml}${q.originalAnswerHtml?`<details><summary>Уточнение к исходному ответу · показать оригинал</summary>${q.originalAnswerHtml}</details>`:''}</div><details class="explanation"><summary>Объяснение и ход рассуждений</summary><div class="rich" style="margin-top:14px">${q.explanationHtml}</div></details>`;}
function source(q){return `<p class="source">${q.origin==='original'?'Исходный README прошлого коллоквиума · '+esc(q.source.topic)+' · №'+q.source.position:esc(q.source.notebook.split('/').pop())+' · лекция '+q.lecture+' · ячейки '+q.source.cells.join(', ')+' (с нуля)'}${q.review?.status==='needs_review'?' · Требует дополнительной проверки':''}</p>`;}
function grading(q){const r=state.session.ratings[q.id];return `<div class="grading">${r?`<p role="status">${r.correct?'✓ Ответ верный':'↻ Нужно повторить'}</p>`:`<div class="button-row">${btn('Ответил правильно','grade','teal','data-correct="true"')}${btn('Ошибся / не смог ответить','grade','','data-correct="false"')}</div>`}</div>`;}
function focusQuestion(){const question=$('view').querySelector('.session-question');if(question){question.scrollIntoView({block:'start',behavior:'instant'});question.focus({preventScroll:true});}}
function sessionView(){const s=state.session;if(!s)return home();const q=byId.get(s.ids[s.index]);if(!q)return empty('Вопрос отсутствует','Начните новую тренировку.');const review=s.mode==='exam'&&s.finished,revealed=review||s.revealed[q.id];return `<div class="session-toolbar"><span class="small muted">${review?'Проверка сохранённого экзамена':s.mode==='voice'?'Голосовая тренировка':'Тренировка'}</span><details class="session-menu"><summary aria-label="Управление тренировкой">⋯</summary><div class="session-menu-items">${btn('Продолжу позже','pause','ghost')}${pendingSession()?btn('Закончить тренировку','end-session','danger'):''}</div></details></div>`+`<div class="session-layout"><article class="card session-question" tabindex="-1" data-question-id="${q.id}"><div class="session-progress"><span>Вопрос ${s.index+1} из ${s.ids.length}</span><div class="bar"><span style="width:${100*(s.index+1)/s.ids.length}%"></span></div></div><div class="badges">${badge(q)}<span class="badge">Лекция ${q.lecture}</span><span class="badge">${esc(q.difficulty)}</span><span class="badge">${esc(q.type)}</span></div><h2 class="question-title">${esc(q.question)}</h2>${q.codeHtml}<p class="small muted">${esc(q.environment)}</p>${s.mode==='voice'?voicePanel(q):revealed?answers(q)+grading(q):`<div class="button-row">${s.mode==='exam'?btn(s.responded.includes(q.id)?'Ответ отмечен':'Я ответил на вопрос','respond','primary'):btn('Показать ответ','reveal','primary')}</div>`}<div class="button-row">${btn('← Предыдущий','previous','',s.index===0||voiceListening||voiceBusy()?'disabled':'')}${btn(s.index===s.ids.length-1?(s.mode==='exam'&&!s.finished?'Завершить экзамен':'Завершить тренировку'):'Следующий →',s.index===s.ids.length-1?'finish':'next','primary',voiceListening||voiceBusy()?'disabled':'')}${btn(state.progress[q.id]?.favorite?'★ В избранном':'☆ Избранное','favorite','ghost',`data-id="${q.id}" aria-pressed="${!!state.progress[q.id]?.favorite}"`)}</div>${source(q)}</article><aside class="card session-aside"><h3>Ваш маршрут</h3><div class="question-dots">${s.ids.map((id,i)=>`<button data-action="jump" data-index="${i}" class="${i===s.index?'current':''} ${s.ratings[id]||s.responded.includes(id)?'done':''}" aria-label="Вопрос ${i+1}" ${i===s.index?'aria-current="step"':''} ${voiceListening||voiceBusy()?'disabled':''}>${i+1}</button>`).join('')}</div><p>${esc(s.reasons[q.id]||'Случайная выборка без повторов внутри варианта.')}</p><p>Оценено ${Object.keys(s.ratings).length} из ${s.ids.length}.</p></aside></div>${review?summary():''}`;}
function summary(){const r=Object.values(state.session.ratings);return `<section class="card" style="margin-top:22px"><h2>${r.length?'Верно '+r.filter(a=>a.correct).length+' из '+r.length+' оценённых':'Ответы открыты для проверки'}</h2><p class="muted small" style="margin-top:10px">Неоценённые вопросы не считаются правильными или ошибочными. ${state.session.mode==='voice'?'Это тренировочная оценка нейросети.':'Это самооценка.'} Результат не является вероятностью сдачи.</p><div class="button-row">${btn('Новая подготовка','leave-session','primary')}${btn('Работа над ошибками','errors')}</div></section>`;}
function lecturePicker(){const rows=stats(config.questions,state).lectures;return btn('← К прогрессу','view','ghost','data-view="progress"')+title('Выберите лекцию.','Откройте вопросы нужной лекции или вернитесь к другой.')+`<div class="lecture-grid">${rows.map(l=>`<button class="card lecture-choice" data-action="open-lecture" data-lecture="${l.lecture}"><span class="lecture-number">${l.lecture}</span><strong>${lectureNames[l.lecture-1]}</strong><span class="small muted">${l.total} вопросов · изучено ${l.seen}</span><span class="lecture-arrow" aria-hidden="true">→</span></button>`).join('')}</div>`;}
function lectureView(){const questions=usable(config.questions).filter(q=>q.lecture===libraryLecture),favorites=questions.filter(q=>state.progress[q.id]?.favorite),rows=onlyFavorites?favorites:questions,expanded=new Set([...$('view').querySelectorAll('.lecture-question[open]')].map(el=>el.dataset.questionId)),answersOpen=new Set([...$('view').querySelectorAll('.lecture-answer[open]')].map(el=>el.dataset.questionId));return btn('← Все лекции','lecture-picker','ghost')+title(`Лекция ${libraryLecture} · ${lectureNames[libraryLecture-1]}`,'Вопросы и ответы этой лекции в одном месте.')+`<div class="lecture-tabs" role="tablist" aria-label="Вопросы лекции">${[['all','Все вопросы',questions.length],['favorites','Избранное',favorites.length]].map(([tab,label,count])=>`<button class="lecture-tab" role="tab" id="lecture-tab-${tab}" data-action="lecture-tab" data-tab="${tab}" aria-selected="${onlyFavorites===(tab==='favorites')}" aria-controls="lecture-question-panel">${label}<span>${count}</span></button>`).join('')}</div><div id="lecture-question-panel" role="tabpanel" aria-labelledby="lecture-tab-${onlyFavorites?'favorites':'all'}" class="question-list">${rows.map((q,i)=>`<details class="card lecture-question" data-question-id="${q.id}" ${expanded.has(q.id)?'open':''}><summary><span class="small muted">Вопрос ${i+1} · ${esc(q.topic)}</span><h3>${esc(q.question)}</h3><span class="lecture-arrow" aria-hidden="true">⌄</span></summary><div class="lecture-question-body"><div class="badges">${badge(q)}<span class="badge">${esc(q.difficulty)}</span><span class="badge">${esc(q.type)}</span></div>${q.codeHtml}<details class="lecture-answer" data-question-id="${q.id}" ${answersOpen.has(q.id)?'open':''}><summary>Показать ответ и объяснение</summary>${answers(q)}</details><div class="button-row">${btn(state.progress[q.id]?.favorite?'★ В избранном':'☆ В избранное','favorite','ghost',`data-id="${q.id}" aria-pressed="${!!state.progress[q.id]?.favorite}"`)}</div></div></details>`).join('')||empty('Здесь пока нет избранного','Добавляйте вопросы звёздочкой во вкладке «Все вопросы».')}</div>`;}

function progress(){const s=stats(config.questions,state),weak=s.lectures.filter(l=>l.attempts>=3&&l.correct/l.attempts<.7),history=paginateHistory(s.history,historyPage);historyPage=history.page;return title('Готовность к экзамену.','Ориентир по вашим ответам и повторениям. Процент правильных ответов не является вероятностью сдачи.')+metrics(s)+`<section class="card"><h2>На что обратить внимание</h2><p class="muted" style="margin-top:14px">${weak.length?weak.map(l=>`Лекция ${l.lecture}: ${lectureNames[l.lecture-1]}`).join('<br>'):'Слабые темы ещё не определены. Для каждой лекции нужны хотя бы три оценённые попытки.'}</p><div class="button-row">${btn('Повторить ошибки','errors','teal')}${btn('Быстрое повторение','quick-review')}</div></section><div class="lecture-grid">${s.lectures.map(l=>`<section class="card"><div class="card-title"><h3>${l.lecture}. ${lectureNames[l.lecture-1]}</h3><span class="badge">Пройдено ${pct(l.seen,l.total)}% · ${l.seen}/${l.total}</span></div><div class="bar"><span style="width:${pct(l.seen,l.total)}%"></span></div><p class="small muted" style="margin-top:12px">Закреплено ${l.mastered} · к повторению ${l.due} · ${l.attempts<3?'Мало данных':`верно ${l.correct} из ${l.attempts}`}</p><div class="button-row">${btn('Все вопросы лекции','open-lecture','teal',`data-lecture="${l.lecture}"`)}</div></section>`).join('')}</div><section class="card history-section" style="margin-top:22px"><h2>История ответов</h2><p class="small muted" style="margin:12px 0 20px">Последние 30 оценок · по 5 на странице.</p><div class="history-list">${history.rows.map(a=>`<article class="history-entry"><div>${byId.has(a.questionId)?btn(esc(historyLabel(byId.get(a.questionId))),'inspect-question','history-question',`data-id="${esc(a.questionId)}"`):'Вопрос из прежней базы'}<p class="small muted">${a.firstAttempt?'Первый ответ':'Повторение'}${a.assessment==='groq'?' · Groq · '+a.score+'/10':''}</p></div><div class="history-meta"><div><span>Дата</span><time datetime="${new Date(a.at).toISOString()}">${new Date(a.at).toLocaleDateString('ru')}</time></div><div><span>Результат</span><strong class="${a.correct?'history-correct':'history-error'}">${a.correct?'Верно':'Ошибка'}</strong></div><div><span>Уверенность</span><strong>${names[a.confidence]||'Не указана'}</strong></div></div></article>`).join('')||empty('Истории пока нет','Оцените первый ответ после сверки с объяснением.')}</div>${history.total?`<nav class="history-pagination" aria-label="Страницы истории">${btn('← Назад','history-prev','',history.page===0?'disabled':'')}<span>Страница ${history.page+1} из ${history.pages}</span>${btn('Далее →','history-next','',history.page===history.pages-1?'disabled':'')}</nav>`:''}</section>`;}

let inspectedQuestion=null;
function historyLabel(q){const topic=q.topic||lectureNames[q.lecture-1];return `Лекция ${q.lecture} · ${topic.length>70?topic.slice(0,70).replace(/\s+\S*$/,'')+'…':topic}`;}
function questionDetails(){const q=byId.get(inspectedQuestion);if(!q)return empty('Вопрос отсутствует','Вернитесь к сборнику.');return title(historyLabel(q),'Вопросы лекции можно просматривать без завершения текущей тренировки.')+`<article class="card session-question"><div class="badges">${badge(q)}<span class="badge">${esc(q.difficulty)}</span><span class="badge">${esc(q.type)}</span></div><h2 class="question-title">${esc(q.question)}</h2>${q.codeHtml}<p class="small muted">${esc(q.environment)}</p><details class="answer"><summary>Показать ответ и объяснение</summary>${answers(q)}</details><div class="button-row">${btn('← К истории ответов','back-progress')}${btn('Ответить в тренировке','open-question','teal',`data-id="${q.id}"`)}</div>${source(q)}</article>`;}

function updateMessage(){return ({checking:'Проверяем обновление…',none:'Обновлений нет. У вас актуальная версия.',ready:'Обновление готово. Нажмите «Применить обновление».',offline:'Нет подключения к интернету. Проверьте обновление позже.',failed:'Не удалось проверить обновление. Проверьте подключение и попробуйте снова.',unavailable:'Проверка обновлений недоступна по этому адресу.'})[registration?.waiting&&!checkingUpdate?'ready':updateStatus]||'';}
function settings(){return title('Всё под вашим контролем.','Прогресс хранится на этом устройстве. Экспорт поможет перенести его или восстановить после очистки браузера.')+`<div class="settings-grid"><section class="card"><h2>Внешний вид</h2><p>Системная тема следует настройке устройства.</p><label class="field">Тема<select id="theme-select">${[['system','Как в системе'],['light','Светлая'],['dark','Тёмная']].map(([v,t])=>`<option value="${v}" ${state.settings.theme===v?'selected':''}>${t}</option>`).join('')}</select></label></section><section class="card"><h2>Перенос прогресса</h2><p>Экспорт включает историю, отметки, настройки и сессию. Импорт заменяет текущий прогресс после проверки файла.</p><div class="button-row">${btn('Экспорт JSON','export','teal')}${btn('Импорт JSON','import')}</div><input id="import-file" type="file" accept="application/json,.json" hidden>${store.rawBackup?btn('Скачать повреждённые данные','export-raw'):''}</section><section class="card"><h2>Установить приложение</h2><p>${location.protocol==='file:'?'Для установки откройте приложение по HTTPS или localhost.':'На iPhone: Safari → Поделиться → На экран «Домой». На Mac: Safari → Файл → Добавить в Dock (если доступно). Chrome и Edge предлагают установку в меню.'}</p><div class="button-row">${btn('Установить','install','teal',!installPrompt?'hidden':'')}</div><p class="small muted" style="margin-top:14px">Офлайн доступен после кэширования. Обновления не очищают прогресс. Safari или пользователь могут удалить локальные данные.</p></section><section class="card"><h2>Обновления</h2><p>Проверьте, доступна ли новая версия приложения.</p><div class="button-row">${btn(checkingUpdate?'Проверяем…':'Проверить обновление','check-update','',checkingUpdate?'disabled':'')}${btn('Применить обновление','apply-update','primary',!registration?.waiting?'hidden':'')}</div><p class="update-result" role="status" aria-live="polite">${updateMessage()}</p></section><section class="card"><h2>Локальные данные</h2><p>Хранилище: ${store.mode==='indexeddb'?'IndexedDB':store.mode==='localstorage'?'резервный localStorage':'только память / недоступно'}. Старые отметки перенесены без вымышленных оценок правильности.</p><div class="button-row">${btn('Очистить прогресс','reset','danger')}</div><p class="small muted" style="margin-top:14px">Перед очисткой сохраните экспорт.</p></section></div>`;}
function enhance(){for(const block of $('view').querySelectorAll('.code-block')){const toolbar=document.createElement('div');toolbar.className='code-toolbar';toolbar.innerHTML='<span>PYTHON</span><button class="btn">Копировать</button>';toolbar.querySelector('button').onclick=async()=>{const text=[...block.querySelectorAll('.line-content')].map(l=>l.textContent).join('\n');try{await navigator.clipboard.writeText(text);toast('Код скопирован');}catch{const t=document.createElement('textarea');t.value=text;t.style.position='fixed';t.style.top='0';document.body.append(t);t.select();const ok=document.execCommand('copy');t.remove();toast(ok?'Код скопирован':'Выделите код и скопируйте вручную');}};block.prepend(toolbar);}if(globalThis.renderMathInElement)renderMathInElement($('view'),{delimiters:[{left:'$$',right:'$$',display:true},{left:'\\[',right:'\\]',display:true},{left:'\\(',right:'\\)',display:false},{left:'$',right:'$',display:false}],throwOnError:false,trust:false,ignoredTags:['script','style','textarea','pre','code']});}
function render(){const oldQuestion=$('view').querySelector('.session-question[data-question-id]')?.dataset.questionId,oldScroll=scrollY;document.body.classList.toggle('in-session',view==='session');for(const b of document.querySelectorAll('[data-view]'))b.classList.toggle('active',b.dataset.view===view||b.dataset.view==='progress'&&['lecture','lectures'].includes(view));$('storage-notice').textContent=storageProblem||store.warning||'';$('view').innerHTML=view==='session'?sessionView():view==='question'?questionDetails():view==='lecture'?lectureView():view==='lectures'?lecturePicker():({home,progress,settings}[view]||home)();enhance();const voiceChat=$('view').querySelector('.voice-chat');if(voiceChat)voiceChat.scrollTop=voiceChat.scrollHeight;if($('theme-select'))$('theme-select').onchange=()=>{state.settings.theme=$('theme-select').value;theme();persist();};for(const id of ['filter-count','filter-origin','smart-mode'])if($(id))$(id).onchange=saveFilters;for(const c of document.querySelectorAll('input[name=lecture],input[name=question-type],input[name=question-level]'))c.onchange=saveFilters;if($('filter-count'))$('filter-count').oninput=saveFilters;if($('import-file'))$('import-file').onchange=importFile;if($('voice-answer'))$('voice-answer').oninput=()=>{const row=oralRecord(state.session.ids[state.session.index]);row[oralField(row)]=$('voice-answer').value;queueDraftSave();};if(view==='session'&&oldQuestion===state.session?.ids[state.session.index])scrollTo({top:oldScroll,behavior:'instant'});}
function saveFilters(){const n=Number($('filter-count').value);if(!Number.isInteger(n)||n<1||n>100){toast('Выберите от 1 до 100 вопросов');return false;}Object.assign(state.settings,{count:n,origin:$('filter-origin').value,smartMode:$('smart-mode').value,types:[...document.querySelectorAll('input[name=question-type]:checked')].map(o=>o.value),levels:[...document.querySelectorAll('input[name=question-level]:checked')].map(o=>o.value),lectures:[...document.querySelectorAll('input[name=lecture]:checked')].map(i=>Number(i.value))});persist();return true;}
async function confirmAction(heading,text,label='Продолжить'){const d=$('confirm-dialog'),opener=document.activeElement;$('dialog-heading').textContent=heading;$('dialog-text').textContent=text;$('dialog-confirm').textContent=label;d.showModal();return new Promise(resolve=>{const finish=value=>{d.close();if(opener?.isConnected&&opener!==$('view'))opener.focus({preventScroll:true});$('dialog-confirm').onclick=null;$('dialog-cancel').onclick=null;d.oncancel=null;resolve(value);};$('dialog-confirm').onclick=()=>finish(true);$('dialog-cancel').onclick=()=>finish(false);d.oncancel=e=>{e.preventDefault();finish(false);};});}
async function start(mode,options={},ids=null){if($('filter-count')&&!saveFilters())return;if(pendingSession()&&!await confirmAction('Начать новую тренировку?','Текущая подборка и незавершённая проверка будут заменены. Оценённые ответы останутся в истории.','Начать новую'))return;const f={...state.settings,...options},timestamp=Date.now(),seed=!state.session&&!state.history.length&&config.seed!==null?config.seed:timestamp;let rows,reasons={};if(ids)rows=ids.map(id=>byId.get(id)).filter(Boolean);else if(options.ticket)rows=ticket(filtered(config.questions,f),seed);else if(mode==='smart'||mode==='voice'){const selection=recommend(config.questions,state,{...f,seed});rows=selection.map(a=>a.question);reasons=Object.fromEntries(selection.map(a=>[a.question.id,a.reason]));}else rows=shuffle(filtered(config.questions,f),seed).slice(0,f.count);if(!rows.length){toast('Нет подходящих вопросов. Измените фильтры или режим.');return;}state.session={id:crypto.randomUUID?.()||timestamp+'-'+Math.random(),mode,ids:rows.map(q=>q.id),index:0,createdAt:timestamp,finished:false,revealed:{},responded:[],ratings:{},confidence:{},reasons,oral:{}};stopVoice();view='session';await persist();render();focusQuestion();}
function download(value,name){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function importFile(e){const file=e.target.files[0];if(!file)return;if(file.size>10*1024*1024){toast('Файл больше 10 МБ');return;}try{const clean=validateImport(JSON.parse(await file.text()),config.questions);if(await confirmAction('Заменить прогресс?','Проверено '+clean.history.length+' оценок. Сохраните текущий экспорт, если хотите оставить обе версии.','Импортировать')){state=clean;await persist();theme();render();toast(storageProblem?'Импорт в памяти; сохранение не удалось':'Прогресс импортирован');}}catch(err){toast('Импорт отменён: '+err.message);}}
async function action(e){const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action,q=state.session&&byId.get(state.session.ids[state.session.index]);
 if(a==='voice-mode')return start('voice');
 if(a==='voice-record'||a==='voice-audio'){voiceError='';try{const row=oralRecord(q.id);if(useAudioByDefault||a==='voice-audio'){voiceAudioUsed=true;await audioRecording.start(row[oralField(row)]);}else dictation.start(row[oralField(row)]);}catch(error){voiceError=error.message;render();}return;}
 if(a==='voice-stop'){if(voiceAudioState==='recording')audioRecording.stop();else dictation.stop();return;}
 if(a==='voice-cancel'){audioRecording.cancel();render();return;}
 if(a==='voice-retry'){voiceError='';const row=oralRecord(q.id);await audioRecording.retry(row[oralField(row)]);return;}
 if(a==='voice-check')return checkVoice(q);
 if(a==='voice-skip'){const result=oralRecord(q.id).turns.at(-1)?.result;if(result)await saveVoiceGrade(q,result);render();return;}
 if(['view','pause','leave-session','open-lecture','lecture-picker','inspect-question','reset','import'].includes(a))stopVoice();
 if(a==='view'){if(b.dataset.view==='progress')historyPage=0;view=b.dataset.view;render();scrollTo({top:0,behavior:'instant'});return;}
 if(a==='start-smart')return start('smart');
 if(a==='originals')return start('practice',{origin:'original',lectures:[],types:[],levels:[]});if(a==='errors')return start('smart',{smartMode:'errors',origin:'all',lectures:[],types:[],levels:[]});if(a==='quick-review')return start('smart',{smartMode:'balanced',origin:'all',lectures:[],types:[],levels:[],count:9,finalReview:true});if(a==='open-question')return start('practice',{},[b.dataset.id]);
 if(a==='open-lecture'){libraryLecture=Number(b.dataset.lecture);onlyFavorites=false;view='lecture';render();scrollTo({top:0,behavior:'instant'});return;}
 if(a==='lecture-picker'){view='lectures';render();scrollTo({top:0,behavior:'instant'});return;}
 if(a==='lecture-tab'){onlyFavorites=b.dataset.tab==='favorites';render();return;}
 if(a==='inspect-question'){inspectedQuestion=b.dataset.id;view='question';render();scrollTo({top:0,behavior:'instant'});return;}
 if(a==='history-prev'||a==='history-next'){historyPage+=a==='history-next'?1:-1;render();$('view').querySelector('.history-section')?.scrollIntoView({block:'start',behavior:'instant'});return;}
 if(a==='back-progress'){view='progress';render();$('view').querySelector('.history-list')?.scrollIntoView({block:'start',behavior:'instant'});return;}
 if(a==='end-session'){if(!pendingSession())return;stopVoice();if(!await confirmAction('Закончить тренировку?','Оценённые ответы и отметки сохранятся. Неоценённые вопросы не будут считаться ошибками.','Закончить тренировку'))return;stopVoice();if(state.session.mode==='voice'){for(const id of state.session.ids){const result=oralRecord(id).turns.at(-1)?.result;if(result&&!state.session.ratings[id])await saveVoiceGrade(byId.get(id),result);}}state.session.finished=true;state.session.completed=true;await persist();view='progress';render();scrollTo({top:0,behavior:'instant'});return;}
 if(a==='resume'){view='session';render();focusQuestion();return;}if(a==='pause'){view='home';await persist();render();scrollTo({top:0,behavior:'instant'});return;}if(a==='leave-session'){view='home';render();return;}
 if(a==='clear-filters'){Object.assign(state.settings,{lectures:[],types:[],levels:[],origin:'all'});await persist();render();return;}if(a==='favorite'||a==='difficult'||a==='studied'){const id=b.dataset.id,p=state.progress[id]||{},field=a==='favorite'?'favorite':a==='studied'?'studied':'difficult';state.progress[id]={...p,[field]:!p[field]};await persist();render();return;}
 if(a==='reveal'){if(state.session.mode==='exam'&&!state.session.finished)return;state.session.revealed[q.id]=true;await persist();render();return;}if(a==='respond'){if(!state.session.responded.includes(q.id))state.session.responded.push(q.id);await persist();render();return;}
 if(a==='confidence'){state.session.confidence||={};state.session.confidence[q.id]=b.dataset.confidence||null;await persist();render();return;}
 if(a==='grade'){if(state.session.mode==='voice'||state.session.ratings[q.id])return;if(state.session.mode==='exam'&&!state.session.finished||!state.session.revealed[q.id]&&state.session.mode!=='exam')return;const c=state.session.confidence?.[q.id]??null,correct=b.dataset.correct==='true';state=recordAnswer(state,q,correct,c,Date.now(),state.session.id);state.session.ratings[q.id]={correct,confidence:c};await persist();render();return;}
 if(a==='next'||a==='previous'||a==='jump'){if(voiceBusy()||voiceListening)return;if(state.session.mode==='voice'){const result=oralRecord(q.id).turns.at(-1)?.result;if(result&&!state.session.ratings[q.id])await saveVoiceGrade(q,result);}stopVoice();state.session.index=a==='jump'?Number(b.dataset.index):Math.max(0,Math.min(state.session.ids.length-1,state.session.index+(a==='next'?1:-1)));await persist();render();focusQuestion();return;}
 if(a==='finish'){if(voiceBusy()||voiceListening)return;if(state.session.mode==='voice'){const result=oralRecord(q.id).turns.at(-1)?.result;if(result&&!state.session.ratings[q.id])await saveVoiceGrade(q,result);}stopVoice();if(state.session.mode==='exam'&&!state.session.finished){if(state.session.responded.length<state.session.ids.length){toast('Отметьте устный ответ на каждый вопрос: '+state.session.responded.length+' из '+state.session.ids.length);return;}state.session.finished=true;state.session.index=0;await persist();render();return;}state.session.finished=true;state.session.completed=true;await persist();view='progress';render();return;}
 if(a==='export'){download({...state,exportedAt:new Date().toISOString()},'python-colloquium-progress.json');return;}if(a==='export-raw'){download(store.rawBackup,'python-colloquium-recovery.json');return;}if(a==='import'){$('import-file').click();return;}
 if(a==='reset'&&await confirmAction('Очистить локальный прогресс?','История, отметки и сессия будут удалены. Сначала сохраните экспорт.','Очистить')){state=freshState();await persist();theme();render();return;}
 if(a==='install'&&installPrompt){await installPrompt.prompt();installPrompt=null;render();return;}if(a==='check-update'){if(checkingUpdate)return;checkingUpdate=true;updateStatus='checking';render();updateStatus=await checkForUpdate(registration,{online:navigator.onLine!==false});checkingUpdate=false;if(view==='settings')render();return;}if(a==='apply-update'&&registration?.waiting){await persist();if(storageProblem){toast('Сначала экспортируйте несохранённую работу');return;}applyUpdate=true;registration.waiting.postMessage({type:'ACTIVATE_UPDATE'});}
}
async function pwa(){if(!('serviceWorker'in navigator)||!['http:','https:'].includes(location.protocol))return;try{registration=await navigator.serviceWorker.register('./sw.js',{scope:'./'});navigator.serviceWorker.addEventListener('controllerchange',()=>{if(applyUpdate)location.reload();});if(registration.waiting){updateStatus='ready';toast('Доступно обновление в настройках.');}registration.addEventListener('updatefound',()=>{const w=registration.installing;w?.addEventListener('statechange',()=>{if(w.state==='installed'){if(registration.waiting)updateStatus='ready';toast(navigator.serviceWorker.controller?'Обновление готово в настройках.':'Ресурсы сохранены для офлайн-подготовки.');if(view==='settings')render();}});});}catch{toast('Офлайн-установка недоступна по этому адресу. Подготовка продолжает работать.');}}
async function main(){store=await openStorage(config.questions);state=store.state;if(!state.updatedAt&&!state.history.length&&!state.session)state.settings.count=config.count||9;$('nav').innerHTML=navigation.map(([id,icon,label])=>`<button data-action="view" data-view="${id}"><span class="nav-icon" aria-hidden="true">${icon}</span>${label}</button>`).join('');document.addEventListener('click',e=>{document.querySelectorAll('.session-menu[open]').forEach(menu=>{if(!menu.contains(e.target))menu.open=false;});action(e).catch(err=>toast(err.message));});$('theme-toggle').onclick=()=>{state.settings.theme=document.documentElement.dataset.theme==='dark'?'light':'dark';theme();persist();};matchMedia('(prefers-color-scheme: dark)').addEventListener('change',()=>{if(state.settings.theme==='system')theme();});window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;if(view==='settings')render();});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden'){if(voiceAudioState!=='permission'&&!dictation.starting)stopVoice();persist();}else if(view==='home'||view==='progress'||view==='session')render();});window.addEventListener('pagehide',()=>{stopVoice();persist();});document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)||$('confirm-dialog').open)return;if(view==='session'&&e.key==='ArrowRight')$('view').querySelector('[data-action=next]')?.click();if(view==='session'&&e.key==='ArrowLeft')$('view').querySelector('[data-action=previous]')?.click();if(view==='session'&&e.code==='Space'&&state.session.mode!=='exam'){e.preventDefault();$('view').querySelector('[data-action=reveal]')?.click();}});theme();render();pwa();}
main().catch(e=>{$('view').textContent='Не удалось запустить приложение: '+e.message;});
